"""create_chunks_table

Revision ID: a3f8f6db89d3
Revises: ce03746823c6
Create Date: 2026-07-17 17:14:03.269799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3f8f6db89d3'
down_revision: Union[str, Sequence[str], None] = 'ce03746823c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('start', sa.Float(), nullable=True))
    op.add_column('chunks', sa.Column('duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'duration')
    op.drop_column('chunks', 'start')
    # ### end Alembic commands ###
